TOPLEVEL_LANG = verilog

SIM = verilator

VERILOG_SOURCES = \
    ../rtl/cnu.sv \
    ../rtl/vnu.sv \
    ../rtl/decoder_iteration.sv

TOPLEVEL = decoder_iteration

MODULE = test_decoder_iteration

include $(shell cocotb-config --makefiles)/Makefile.sim